image: go1.3
env:
  - GOPATH=/var/cache/drone
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
  - POSTGRES_TEST_URL=user=gorptest password=gorptest dbname=gorptest host=localhost sslmode=disable
  - MY_MYSQL_TEST_URL=gorptest/root/
  - MYSQL_TEST_URL=root@/gorptest
  - SQLITE_TEST_URL=/tmp/gorptest.bin
script:
  - mysql -u root -h 127.0.0.1 -e "create database gorptest"
  - mysql -u root -h 127.0.0.1 -e "grant all on gorptest.* to gorptest@localhost identified by 'gorptest'"
  - psql -U postgres -h 127.0.0.1 -c "create user gorptest password 'gorptest'"
  - psql -U postgres -h 127.0.0.1 -c "create database gorptest owner gorptest"
  -
  - ./drone_go_version_update.sh
  - go version
  - go get -t ./...
  - go build ./...
  - ./combined_coverage_tests.sh
services:
  - postgres
  - mysql
